# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_model_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setObjectName("verticalWidget")
        self.mainWidget = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.mainWidget.setObjectName("mainWidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.verticalWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.formLayoutWidget = QtWidgets.QWidget(self.homePage)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 40, 341, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.loginForm = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.loginForm.setContentsMargins(0, 0, 0, 0)
        self.loginForm.setObjectName("loginForm")
        self.accountLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.accountLabel_2.setMinimumSize(QtCore.QSize(0, 34))
        self.accountLabel_2.setObjectName("accountLabel_2")
        self.loginForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.accountLabel_2)
        self.loginName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.loginName.setMinimumSize(QtCore.QSize(0, 34))
        self.loginName.setAutoFillBackground(False)
        self.loginName.setStyleSheet("border:1 solid #ff6700;border-radius:5;")
        self.loginName.setObjectName("loginName")
        self.loginForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loginName)
        self.passwordLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.passwordLabel_2.setMinimumSize(QtCore.QSize(0, 34))
        self.passwordLabel_2.setText("")
        self.passwordLabel_2.setObjectName("passwordLabel_2")
        self.loginForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel_2)
        self.Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label.setObjectName("Label")
        self.loginForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.loginPassword = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.loginPassword.setMinimumSize(QtCore.QSize(0, 34))
        self.loginPassword.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.loginPassword.setStyleSheet("border:1 solid #ff6700;border-radius:5;")
        self.loginPassword.setObjectName("loginPassword")
        self.loginForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.loginPassword)
        self.loginButton = QtWidgets.QPushButton(self.homePage)
        self.loginButton.setGeometry(QtCore.QRect(280, 210, 90, 36))
        self.loginButton.setMinimumSize(QtCore.QSize(90, 36))
        self.loginButton.setObjectName("loginButton")
        self.loginLabel = QtWidgets.QLabel(self.homePage)
        self.loginLabel.setGeometry(QtCore.QRect(30, 180, 341, 20))
        self.loginLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.loginLabel.setText("")
        self.loginLabel.setObjectName("loginLabel")
        self.stackedWidget.addWidget(self.homePage)
        self.resultPage = QtWidgets.QWidget()
        self.resultPage.setObjectName("resultPage")
        self.stackedWidget.addWidget(self.resultPage)
        self.mainWidget.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.verticalWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.accountLabel_2.linkActivated['QString'].connect(self.loginName.selectAll)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.accountLabel_2.setText(_translate("MainWindow", "登录名"))
        self.Label.setText(_translate("MainWindow", "密码"))
        self.loginButton.setText(_translate("MainWindow", "登录"))
